package backend

type Comment struct {
	Grade1 []string
	Grade2 []string
	Grade3 []string
	Grade4 []string
	Grade5 []string
}

type ScoreCommentDetails struct {
	JobKnowledge   Comment
	QualityOfWork  Comment
	QuantityOfWork Comment
	Initiative     Comment
	Teamwork       Comment
	Safety         Comment
	Responsiblity  Comment
	Attendance     Comment
}

var ScoreComments = &ScoreCommentDetails{
	JobKnowledge:   jobKnowledgeCommetns,
	QualityOfWork:  qualityOfWorkComments,
	QuantityOfWork: quantityOfWorkComments,
	Initiative:     initiativeComments,
	Teamwork:       teamworkComments,
	Responsiblity:  responsiblityComments,
	Safety:         safetyComments,
	Attendance:     attendanceComments,
}

var attendanceComments = Comment{
	Grade1: []string{
		"Has been consistently late or absent without a valid reason, resulting in significant disruptions to team productivity.",
		"Shows a pattern of tardiness and absenteeism, often without prior notification or explanation.",
		"Has demonstrated a lack of respect for team members' time by consistently arriving late or not showing up at all.",
		"Frequently arrives late or leaves early without prior notice or approval, causing disruptions to team projects and deadlines.",
		"Has a poor attendance record, often failing to show up for work without explanation or warning.",
		"Regularly misses deadlines or shows up late to meetings, causing unnecessary delays and disruptions.",
		"Shows a lack of commitment to the team by failing to show up for work or arriving late on a consistent basis.",
		"Has failed to demonstrate basic punctuality and attendance requirements, resulting in a negative impact on team morale and productivity.",
		"Consistently fails to meet attendance and punctuality requirements, despite repeated reminders and warnings.",
		"Has demonstrated a complete lack of respect for the company's attendance and punctuality policies, resulting in disciplinary action.",
	},
	Grade2: []string{
		"Occasionally arrives late or leaves early without prior notification, but generally shows up on time and meets attendance requirements.",
		"Has had a few instances of tardiness or absenteeism but has generally been punctual and dependable.",
		"Shows a willingness to make up missed time or work extra hours when necessary to ensure that deadlines are met.",
		"Has a good attendance record overall, but may occasionally be late or absent due to unforeseen circumstances.",
		"Generally meets attendance and punctuality requirements, but may need occasional reminders to stay on track.",
		"Demonstrates a basic understanding of the importance of punctuality and attendance, but may need additional coaching to improve in this area.",
		"Has generally met attendance and punctuality requirements, but may need additional support to consistently meet expectations.",
		"Shows a commitment to improving attendance and punctuality, and actively seeks feedback on how to better meet expectations.",
		"Has demonstrated a willingness to take ownership of attendance and punctuality, and consistently meets requirements with minimal supervision.",
		"Consistently meets attendance and punctuality requirements, and actively works to ensure that the team's productivity and morale are not impacted.",
	},
	Grade3: []string{
		"Generally arrives on time and meets attendance requirements, but may occasionally need reminders to stay on track.",
		"Has a good attendance record and demonstrates a basic understanding of the importance of punctuality and attendance.",
		"Consistently meets attendance and punctuality requirements, and shows a willingness to make up missed time or work extra hours when necessary.",
		"Demonstrates a commitment to improving attendance and punctuality, and seeks feedback on how to better meet expectations.",
		"Shows a proactive approach to managing attendance and punctuality, and takes steps to ensure that disruptions are minimized.",
		"Has demonstrated a strong understanding of the importance of attendance and punctuality, and consistently meets expectations with minimal supervision.",
		"Actively supports the team by ensuring that attendance and punctuality requirements are consistently met, even in challenging situations.",
		"Consistently meets or exceeds attendance and punctuality requirements, and serves as a role model for other team members.",
		"Has a strong sense of responsibility and ownership over attendance and punctuality, and consistently goes above and beyond to ensure that expectations are met.",
		"Demonstrates exceptional leadership in managing attendance and punctuality, and actively supports and mentors others to improve in this area.",
	},
	Grade4: []string{
		"Attendance and punctuality could be improved. Occasional tardiness and absences may have caused inconvenience for colleagues and the company.",
		"Attendance and punctuality are generally good but could still be improved in some areas. Occasionally arrives a few minutes late, but does not cause major disruptions.",
		"Attendance is generally good but punctuality could be improved. Employee has been tardy a few times but usually catches up quickly.",
		"Attendance is generally good with only a few minor lapses in punctuality. Employee arrives on time but occasionally leaves a few minutes early.",
		"Attendance and punctuality are good. Employee is usually on time and very rarely absent without prior notice.",
		"Attendance and punctuality are excellent. Employee is always on time and never misses work without prior notice or a valid reason.",
		"Attendance and punctuality are exceptional. Employee has never been late or absent without prior notice in the entire review period.",
		"Attendance and punctuality are outstanding. Employee consistently arrives early and is always present for work, even in adverse weather conditions or other unexpected circumstances.",
		"Attendance and punctuality are exemplary. Employee has set a high standard for others to follow with consistent early arrivals and perfect attendance throughout the review period.",
		"Attendance and punctuality are flawless. Employee has demonstrated exceptional commitment to their work by arriving early, staying late, and never missing a day of work.",
	},
	Grade5: []string{
		"Attendance and punctuality are consistently outstanding. Employee has never been late or absent without prior notice in the entire duration of their employment.",
		"Attendance and punctuality are exemplary. Employee always arrives early and is always present for work, even in adverse weather conditions or other unexpected circumstances.",
		"Attendance and punctuality are exceptional. Employee has set a high standard for others to follow with consistent early arrivals and perfect attendance throughout the review period.",
		"Attendance and punctuality are flawless. Employee has demonstrated exceptional commitment to their work by arriving early, staying late, and never missing a day of work.",
		"Attendance and punctuality are exceptional. Employee always arrives early and never misses work, even in emergencies or other unexpected situations.",
		"Attendance and punctuality are excellent. Employee is always on time and never misses work without prior notice or a valid reason.",
		"Attendance and punctuality are excellent. Employee consistently arrives early and is always present for work, even in adverse weather conditions or other unexpected circumstances.",
		"Attendance and punctuality are outstanding. Employee always arrives early and never misses work without prior notice or a valid reason.",
		"Attendance and punctuality are outstanding. Employee consistently arrives early and is always present for work, even in adverse weather conditions or other unexpected circumstances.",
		"Attendance and punctuality are flawless. Employee has demonstrated exceptional commitment to their work by arriving early, staying late, and never missing a day of work.",
	},
}

var safetyComments = Comment{
	Grade1: []string{
		"Fails to follow safety protocols, putting themselves and others at risk",
		"Does not show concern for cleanliness and organization in the workplace",
		"Shows disregard for company resources and does not make an effort to minimize costs",
		"Needs to be reminded repeatedly about safety procedures and cost-saving measures",
		"Fails to take responsibility for maintaining a safe and cost-effective workplace",
		"Consistently leaves work areas messy and disorganized",
		"Does not demonstrate any effort to reduce waste or unnecessary spending",
		"Shows little regard for maintaining a safe and efficient work environment",
		"Fails to report safety concerns or potential hazards",
		"Does not take initiative to improve the cleanliness, safety, or cost-effectiveness of the workplace",
	},
	Grade2: []string{
		"Occasionally neglects to follow safety procedures or take necessary precautions",
		"Needs reminders to keep work areas clean and tidy",
		"Could be more proactive in identifying opportunities to save costs",
		"Generally follows safety protocols, but may require some oversight",
		"Maintains a basic level of organization in their work area",
		"Makes some effort to minimize waste and reduce unnecessary spending",
		"Shows some concern for maintaining a safe and efficient work environment",
		"Reports safety concerns and potential hazards when they arise",
		"Takes some initiative to improve the cleanliness, safety, or cost-effectiveness of the workplace",
		"Demonstrates a basic understanding of the importance of housekeeping, safety, and cost-consciousness",
	},
	Grade3: []string{
		"Follows safety protocols and takes necessary precautions",
		"Keeps work areas clean and tidy most of the time",
		"Considers cost-saving measures when making decisions, but could do more",
		"Generally takes responsibility for maintaining a safe and efficient work environment",
		"Maintains an organized work area",
		"Makes efforts to minimize waste and unnecessary spending",
		"Reports safety concerns and potential hazards promptly",
		"Takes some initiative to improve the cleanliness, safety, or cost-effectiveness of the workplace",
		"Demonstrates an understanding of the importance of housekeeping, safety, and cost-consciousness",
		"Generally meets expectations in this area",
	},
	Grade4: []string{
		"Consistently follows safety protocols and takes necessary precautions",
		"Keeps work areas clean and tidy at all times",
		"Actively looks for ways to save costs without compromising quality",
		"Takes responsibility for maintaining a safe and efficient work environment",
		"Maintains an organized work area",
		"Makes consistent efforts to minimize waste and unnecessary spending",
		"Reports safety concerns and potential hazards promptly and takes corrective action when necessary",
		"Takes initiative to improve the cleanliness, safety, or cost-effectiveness of the workplace",
		"Understands and consistently demonstrates the importance of housekeeping, safety, and cost-consciousness",
		"Consistently exceeds expectations in this area",
	},
	Grade5: []string{
		"Demonstrates an exceptional level of attention to detail in maintaining a clean and safe work environment.",
		"Proactively identifies potential safety hazards and takes appropriate measures to prevent accidents.",
		"Shows a strong commitment to cost-consciousness by consistently seeking ways to reduce waste and optimize efficiency.",
		"Consistently goes above and beyond in ensuring that all equipment and tools are properly maintained and stored.",
		"Takes an active role in identifying cost-saving opportunities and implementing them to improve overall efficiency.",
		"Maintains a meticulous level of organization in the workplace, resulting in a highly efficient and productive environment.",
		"Demonstrates exceptional care and concern for the safety of all team members, taking extra steps to ensure their well-being.",
		"Actively seeks out ways to minimize waste and reduce costs without sacrificing quality or safety.",
		"Takes ownership of the workplace and its resources, treating everything with the utmost respect and care.",
		"Regularly seeks feedback and implements suggestions for improvement to ensure that the workplace is always at its best.",
	},
}

var initiativeComments = Comment{
	Grade1: []string{
		"Frequently requires guidance and direction to perform tasks",
		"Rarely takes on new tasks or responsibilities without being told to do so",
		"Shows little initiative and does only what is required",
		"Consistently needs reminders to complete tasks on time",
		"Rarely seeks out new opportunities or ways to improve work performance",
		"Does not take ownership of problems and relies heavily on others for solutions",
		"Does not take the initiative to learn new skills or technologies",
		"Seldom contributes new ideas or suggestions for improvement",
		"Needs constant supervision and direction to complete tasks",
		"Does not take the initiative to help others or go above and beyond job duties",
	},
	Grade2: []string{
		"Occasionally takes on new tasks or responsibilities without being told to do so",
		"May require some guidance or direction to perform new tasks",
		"Shows some initiative and goes beyond what is required occasionally",
		"Usually completes tasks on time without reminders",
		"Occasionally seeks out new opportunities or ways to improve work performance",
		"Will take ownership of problems when asked, but does not always proactively do so",
		"Willing to learn new skills and technologies, but may need some encouragement",
		"Occasionally contributes new ideas or suggestions for improvement",
		"Can work independently, but may need some guidance or direction",
		"Willing to help others or go above and beyond job duties occasionally",
	},
	Grade3: []string{
		"Takes on new tasks or responsibilities without being told to do so",
		"Requires minimal guidance or direction to perform new tasks",
		"Shows initiative and goes beyond what is required occasionally",
		"Consistently completes tasks on time without reminders",
		"Frequently seeks out new opportunities or ways to improve work performance",
		"Will take ownership of problems and proactively seek solutions",
		"Willing to learn new skills and technologies",
		"Frequently contributes new ideas or suggestions for improvement",
		"Can work independently with minimal guidance or direction",
		"Willing to help others or go above and beyond job duties",
	},
	Grade4: []string{
		"Takes on new tasks or responsibilities without being told to do so",
		"Requires minimal guidance or direction to perform new tasks",
		"Consistently shows initiative and goes beyond what is required",
		"Always completes tasks on time without reminders",
		"Proactively seeks out new opportunities or ways to improve work performance",
		"Takes ownership of problems and consistently finds solutions",
		"Quickly learns new skills and technologies",
		"Consistently contributes new ideas or suggestions for improvement",
		"Works independently with minimal guidance or direction",
		"Always willing to help others or go above and beyond job duties",
	},
	Grade5: []string{
		"Proactively takes on new tasks or responsibilities without being told to do so",
		"Requires no guidance or direction to perform new tasks",
		"Consistently shows exceptional initiative and goes above and beyond what is required",
		"Always completes tasks on time or ahead of schedule without reminders",
		"Consistently seeks out and implements new opportunities or ways to improve work performance",
		"Takes full ownership of problems and consistently finds innovative solutions",
		"Quickly and independently learns new skills and technologies",
		"Consistently contributes new and valuable ideas or suggestions for improvement",
		"Works independently with exceptional skill and judgment",
		"Always willing to help others or go above and beyond job duties in exceptional ways",
	},
}

var jobKnowledgeCommetns = Comment{
	Grade1: []string{
		"Lacks knowledge of job responsibilities and requires constant supervision.",
		"Difficulty performing tasks independently and requires significant training.",
		"Poor job knowledge is impacting the team's performance.",
		"Frequently makes mistakes and is unable to complete tasks on their own.",
		"Poor job knowledge is hindering their ability to contribute to the organization.",
		"Lack of understanding of job responsibilities is a serious concern.",
		"Not able to carry out duties without constant direction from their supervisor.",
		"Lack of knowledge is causing delays and errors in work.",
		"Performance is significantly impacted by poor job knowledge.",
		"Lack of expertise is impacting the quality of work.",
	},
	Grade2: []string{
		"Has a limited understanding of job responsibilities and requires significant guidance.",
		"Requires regular supervision to ensure work meets required standards.",
		"Job knowledge could be improved with additional training and guidance.",
		"Difficulty completing complex tasks independently.",
		"Performance is inconsistent and requires further development.",
		"Job knowledge is a potential area for improvement.",
		"Room to improve understanding of job responsibilities.",
		"Requires guidance on more complex tasks.",
		"Needs additional training to improve job knowledge.",
		"Job knowledge is impacting productivity and efficiency.",
	},
	Grade3: []string{
		"Has a satisfactory understanding of job responsibilities and industry-specific knowledge.",
		"Requires minimal supervision to complete tasks effectively.",
		"Consistently produces work that meets or exceeds expectations.",
		"Demonstrates a good understanding of job responsibilities and can apply knowledge effectively.",
		"Capable of completing complex tasks independently.",
		"Performs work accurately and efficiently.",
		"Job knowledge is a strong asset to the team.",
		"Proactively seeks out additional training to improve job knowledge.",
		"Capable of sharing job knowledge with others on the team.",
		"Job knowledge is a key contributor to the organization's success.",
	},
	Grade4: []string{
		"Has an excellent understanding of job responsibilities and industry-specific knowledge.",
		"Demonstrates a deep understanding of job requirements and can apply knowledge effectively.",
		"Consistently exceeds expectations and produces high-quality work.",
		"Demonstrates the ability to think creatively and solve complex problems.",
		"Capable of mentoring and training others on the team.",
		"Job knowledge is a significant asset to the organization.",
		"Actively seeks out opportunities to expand job knowledge and skills.",
		"Consistently finds ways to improve processes and workflows.",
		"Demonstrates a deep commitment to personal and professional development.",
		"Job knowledge is a key driver of organizational success.",
	},
	Grade5: []string{
		"Has an exceptional understanding of job responsibilities and industry-specific knowledge.",
		"Demonstrates mastery of job requirements and can apply knowledge in innovative ways.",
		"Produces work that consistently exceeds expectations and sets a high standard for others on the team.",
		"Consistently finds ways to improve productivity and efficiency.",
		"Capable of leading and driving change in the organization.",
		"Job knowledge is a critical component of the organization's success.",
		"Actively seeks out opportunities to innovate and improve processes and workflows.",
		"Demonstrates exceptional problem-solving skills and the ability to think strategically.",
		"Highly sought-after as a mentor and thought leader in the organization.",
		"Job knowledge is a key driver of innovation and growth for the organization.",
	},
}

var qualityOfWorkComments = Comment{
	Grade1: []string{
		"Produces work that consistently falls short of expected quality standards.",
		"Frequently makes errors that impact the accuracy of work.",
		"Struggles to identify and correct errors in work.",
		"Has difficulty following instructions and completing work as requested.",
		"Produces work that lacks clarity and is difficult to understand.",
		"Consistently misses deadlines and fails to prioritize tasks effectively.",
		"Does not seek feedback or take steps to improve work quality.",
		"Lacks attention to detail and frequently overlooks important details.",
		"Work is consistently inconsistent and varies in quality.",
		"Has little to no impact on organizational goals and objectives.",
	},
	Grade2: []string{
		"Produces work that meets basic quality standards but lacks attention to detail.",
		"Occasionally makes errors that require correction.",
		"Struggles to consistently meet deadlines and prioritize tasks effectively.",
		"Follows instructions but may require additional guidance to complete work as requested.",
		"Demonstrates some initiative in identifying and correcting errors in work.",
		"Produces work that is generally clear but may require clarification in some areas.",
		"Demonstrates a willingness to seek feedback and improve work quality.",
		"Work quality is inconsistent and may vary in accuracy and completeness.",
		"Has a limited impact on organizational goals and objectives.",
		"Requires further development to consistently produce quality work.",
	},
	Grade3: []string{
		"Produces work that consistently meets quality standards and is generally accurate.",
		"Demonstrates attention to detail and produces work that is clear and easy to understand.",
		"Consistently meets deadlines and prioritizes tasks effectively.",
		"Follows instructions and requires minimal guidance to complete work as requested.",
		"Identifies errors in work and takes steps to correct them proactively.",
		"Demonstrates some initiative in identifying opportunities to improve work quality.",
		"Seeks feedback and takes steps to improve work quality based on feedback received.",
		"Work quality is generally consistent and reliable.",
		"Has a positive impact on organizational goals and objectives.",
		"Demonstrates a solid foundation of quality work and has potential for further growth.",
	},
	Grade4: []string{
		"Produces work that consistently exceeds quality standards and demonstrates attention to detail.",
		"Demonstrates a high level of accuracy in work and produces work that is clear and concise.",
		"Consistently meets or exceeds deadlines and effectively prioritizes tasks.",
		"Follows instructions accurately and consistently without requiring guidance.",
		"Identifies and proactively resolves errors in work to maintain high quality standards.",
		"Demonstrates initiative in identifying opportunities to improve work quality and processes.",
		"Actively seeks feedback and incorporates feedback to improve work quality.",
		"Consistently produces high-quality work that is reliable and consistent.",
		"Has a significant impact on organizational goals and objectives.",
		"Consistently produces work of exceptional quality and sets a high standard for others.",
	},
	Grade5: []string{
		"Produces work that consistently exceeds quality standards and demonstrates exceptional attention to detail.",
		"Demonstrates mastery in accuracy and produces work that is clear, concise, and impactful.",
		"Consistently exceeds deadlines and effectively prioritizes tasks to maximize productivity.",
		"Follows instructions with exceptional accuracy and consistency.",
		"Proactively identifies and resolves errors in work to maintain the highest quality standards.",
		"Consistently demonstrates initiative in identifying and implementing opportunities for process improvement.",
		"Actively seeks feedback and proactively incorporates feedback to improve work quality and performance.",
		"Consistently produces work that is of the highest quality and reliability.",
		"Has a significant impact on organizational goals and objectives.",
		"Consistently produces exceptional work that sets a high standard for others to follow.",
	},
}

var quantityOfWorkComments = Comment{
	Grade1: []string{
		"Consistently fails to meet established production goals and output requirements.",
		"Produces work output that is significantly below the acceptable level of performance.",
		"Consistently fails to complete work assignments in a timely and efficient manner.",
		"Frequently requires assistance or redirection to complete basic job tasks.",
		"Produces work output that is often incomplete or of poor quality.",
		"Consistently requires extensive supervision and coaching to complete work tasks.",
		"Produces work output that requires significant revision and correction.",
		"Consistently struggles to meet even the most basic job requirements and performance expectations.",
		"Requires significant improvement in productivity and output to meet job requirements.",
		"Produces work output that is consistently below the minimum acceptable level of performance.",
	},
	Grade2: []string{
		"Produces work output that meets the basic requirements of the job but is often incomplete or of poor quality.",
		"Frequently requires reminders or follow-up to complete work tasks on time.",
		"Consistently meets minimum job requirements but fails to exceed expectations.",
		"Produces work output that is occasionally inconsistent or requires significant revision.",
		"Requires occasional supervision and direction to complete work assignments.",
		"Occasionally fails to meet established production goals and output requirements.",
		"Produces work output that meets the minimum level of performance but often lacks creativity or innovation.",
		"Consistently meets job requirements but could benefit from additional training or coaching.",
		"Produces work output that is generally satisfactory but may require some revision or refinement.",
		"Occasionally exceeds job requirements but lacks consistency in achieving high levels of productivity.",
	},
	Grade3: []string{
		"Consistently meets established production goals and output requirements.",
		"Produces work output that meets the acceptable level of performance and quality standards.",
		"Occasionally exceeds performance expectations and produces work output that demonstrates initiative and innovation.",
		"Requires minimal supervision and direction to complete work tasks.",
		"Produces work output that is generally consistent and requires minimal revision or refinement.",
		"Demonstrates a good understanding of job requirements and consistently meets or exceeds expectations.",
		"Produces work output that is generally of good quality and meets or exceeds established performance standards.",
		"Consistently meets job requirements and is able to effectively prioritize work assignments.",
		"Produces work output that is generally reliable and meets the needs of the organization.",
		"Occasionally requires additional coaching or training to meet job requirements or exceed expectations.",
	},
	Grade4: []string{
		"Consistently exceeds established production goals and output requirements.",
		"Produces work output that consistently meets or exceeds quality standards.",
		"Consistently demonstrates initiative and innovation in work assignments.",
		"Produces work output that is consistently accurate, complete, and meets established performance standards.",
		"Requires minimal supervision or direction and consistently meets or exceeds performance expectations.",
		"Produces work output that is generally reliable and meets or exceeds the needs of the organization.",
		"Demonstrates a good understanding of job requirements and consistently exceeds expectations.",
		"Produces work output that is consistently of the highest quality and reliability.",
		"Consistently exceeds job requirements and contributes significantly to the success of the organization.",
		"Produces work output that consistently exceeds expectations and sets a high standard for others to follow.",
	},
	Grade5: []string{
		"Consistently produces work output that significantly exceeds established performance standards and expectations.",
		"Demonstrates exceptional productivity and consistently exceeds production goals and output requirements.",
		"Consistently demonstrates initiative and innovation in identifying opportunities for increased productivity and efficiency.",
		"Produces work output that is consistently accurate, complete, and of the highest quality.",
		"Consistently meets or exceeds job requirements without the need for supervision or direction.",
		"Produces work output that consistently exceeds expectations and sets a high standard for others to follow.",
		"Demonstrates a commitment to continuous improvement and consistently looks for ways to enhance work processes and productivity.",
		"Consistently exceeds job requirements and contributes significantly to the success of the organization.",
		"Produces work output that consistently meets or exceeds the needs of the organization and exceeds customer expectations.",
		"Is a role model for productivity and consistently produces work output that is of the highest quality and reliability.",
	},
}

var teamworkComments = Comment{
	Grade1: []string{
		"Rarely or never shows willingness to work collaboratively with colleagues.",
		"Consistently acts in a manner that is detrimental to team cohesion and productivity.",
		"Frequently disregards the needs and concerns of other team members.",
		"Has a negative attitude towards team members and the organization.",
		"Consistently fails to contribute to team goals and objectives.",
		"Demonstrates a lack of respect for other team members and their contributions.",
		"Frequently undermines team decisions and actions.",
		"Is a consistent hindrance to effective teamwork and cooperation.",
		"Does not actively participate in team meetings or discussions.",
		"Rarely offers assistance or support to other team members.",
	},
	Grade2: []string{
		"Occasionally shows willingness to work collaboratively with colleagues.",
		"Sometimes acts in a manner that is detrimental to team cohesion and productivity.",
		"Occasionally disregards the needs and concerns of other team members.",
		"Has a neutral attitude towards team members and the organization.",
		"Sometimes fails to contribute to team goals and objectives.",
		"Demonstrates some respect for other team members and their contributions.",
		"Sometimes undermines team decisions and actions.",
		"Can be a hindrance to effective teamwork and cooperation.",
		"Participates in team meetings or discussions to a limited extent.",
		"Sometimes offers assistance or support to other team members.",
	},
	Grade3: []string{
		"Usually shows willingness to work collaboratively with colleagues.",
		"Generally acts in a manner that is conducive to team cohesion and productivity.",
		"Usually takes into consideration the needs and concerns of other team members.",
		"Has a generally positive attitude towards team members and the organization.",
		"Usually contributes to team goals and objectives.",
		"Demonstrates respect for other team members and their contributions.",
		"Occasionally questions team decisions and actions.",
		"Can be an asset to effective teamwork and cooperation.",
		"Participates in team meetings or discussions on a regular basis.",
		"Usually offers assistance or support to other team members.",
	},
	Grade4: []string{
		"Consistently shows willingness to work collaboratively with colleagues.",
		"Consistently acts in a manner that is conducive to team cohesion and productivity.",
		"Consistently takes into consideration the needs and concerns of other team members.",
		"Has a consistently positive attitude towards team members and the organization.",
		"Consistently contributes to team goals and objectives.",
		"Consistently demonstrates respect for other team members and their contributions.",
		"Occasionally takes a leadership role in team decision-making and action.",
		"Is a strong asset to effective teamwork and cooperation.",
		"Actively participates in team meetings or discussions.",
		"Consistently offers assistance or support to other team members.",
	},
	Grade5: []string{
		"Exemplifies teamwork and cooperation in all aspects of work.",
		"Consistently goes above and beyond to support team members and contribute to team goals and objectives.",
		"Demonstrates an exceptional ability to work collaboratively with colleagues from diverse backgrounds and disciplines.",
		"Consistently shows a high level of respect for other team members and their contributions.",
		"Demonstrates outstanding leadership in team decision-making and action.",
		"Is a key contributor to effective teamwork and cooperation throughout the organization.",
		"Consistently takes an active role in promoting a positive team culture and work environment.",
		"Is highly regarded by team members and is often sought out for advice and assistance.",
		"Takes ownership of team objectives and strives for excellence in team performance.",
		"Fosters an inclusive and supportive team environment that encourages collaboration and innovation.",
	},
}

var responsiblityComments = Comment{
	Grade1: []string{
		"Does not take responsibility for completing assigned tasks.",
		"Frequently misses deadlines and commitments.",
		"Needs constant reminders and follow-up to complete tasks.",
		"Has difficulty prioritizing tasks and often fails to complete high-priority work on time.",
		"Has a tendency to blame others for mistakes and shortcomings.",
		"Fails to take ownership of mistakes and often tries to shift responsibility onto others.",
		"Regularly fails to show up for work or meetings without prior notice.",
		"Does not take necessary steps to ensure the quality and accuracy of work.",
		"Has a negative attitude towards responsibility and often avoids taking on new challenges.",
		"Lacks the ability to be relied upon for important tasks and assignments.",
	},
	Grade2: []string{
		"Occasionally needs reminders to complete tasks and meet deadlines.",
		"Generally completes assigned work on time and to an acceptable standard.",
		"Is able to prioritize tasks effectively but may struggle with high-priority or complex work.",
		"Takes responsibility for mistakes and shortcomings but may need guidance to address them.",
		"Is reliable in showing up for work and meetings but may occasionally miss due to unforeseen circumstances.",
		"Demonstrates a willingness to take on new responsibilities and challenges.",
		"Shows a basic understanding of quality standards and takes steps to ensure work meets them.",
		"Generally maintains a positive attitude towards responsibility and accountability.",
		"Can be relied upon for most tasks and assignments but may require occasional supervision or guidance.",
		"Is generally dependable but may have occasional lapses in reliability.",
	},
	Grade3: []string{
		"Usually completes assigned tasks on time and to a high standard.",
		"Demonstrates an ability to prioritize tasks effectively and handle high-priority or complex work.",
		"Takes responsibility for mistakes and shortcomings and works to address them independently.",
		"Is reliable in showing up for work and meetings and gives notice when unable to attend.",
		"Demonstrates a willingness to take on new responsibilities and challenges, and seeks out opportunities to grow.",
		"Shows a good understanding of quality standards and takes steps to ensure work meets them consistently.",
		"Maintains a positive attitude towards responsibility and accountability.",
		"Can be relied upon for most tasks and assignments with minimal supervision or guidance.",
		"Is generally dependable and consistently meets expectations.",
		"Takes ownership of tasks and assignments and strives for excellence in all work.",
	},
	Grade4: []string{
		"Consistently completes assigned tasks on time and to a high standard.",
		"Demonstrates exceptional ability to prioritize tasks and handle high-priority or complex work independently.",
		"Takes responsibility for mistakes and shortcomings and proactively works to address them.",
		"Is consistently reliable in showing up for work and meetings and gives ample notice when unable to attend.",
		"Actively seeks out new responsibilities and challenges and contributes to team and organizational goals.",
		"Demonstrates a thorough understanding of quality standards and consistently exceeds them.",
		"Maintains a positive attitude towards responsibility and accountability and is a role model for others.",
		"Can be relied upon for all tasks and assignments with minimal supervision or guidance.",
		"Is highly dependable and consistently exceeds expectations.",
		"Takes ownership of tasks and assignments and strives for excellence in all work.",
	},
	Grade5: []string{
		"Consistently meets deadlines and fulfills commitments without reminders",
		"Takes responsibility for own actions and mistakes without being prompted",
		"Reliable and trustworthy, colleagues can always count on them",
		"Exercises good judgment and makes wise decisions in difficult situations", "Goes above and beyond to ensure tasks are completed to the highest standard", "Displays a strong sense of ownership and accountability in their work", "Demonstrates exceptional dedication and commitment to their responsibilities", "Anticipates potential problems and takes proactive steps to avoid them", "Handles confidential information with utmost discretion and confidentiality",
		"Consistently demonstrates a positive attitude and strong work ethic",
	},
}
