// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAverageScores(arg1:any):Promise<any>;

export function GenerateScoreDetails(arg1:any):Promise<any>;

export function GetDataFromExcel(arg1:string,arg2:string):Promise<Array<any>>;

export function GetExcelSheets(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InitEmployeeData(arg1:string,arg2:string):Promise<Array<any>>;

export function OpenDirForExcelFile():Promise<string>;

export function ResetScoreDetails(arg1:any):Promise<any>;
