// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertJsonToExcel(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertJsonToExcel'](arg1, arg2, arg3);
}

export function GenerateAllEmployeeData(arg1) {
  return window['go']['main']['App']['GenerateAllEmployeeData'](arg1);
}

export function GenerateAverageScores(arg1) {
  return window['go']['main']['App']['GenerateAverageScores'](arg1);
}

export function GenerateNonExecAppraisalPDF(arg1, arg2) {
  return window['go']['main']['App']['GenerateNonExecAppraisalPDF'](arg1, arg2);
}

export function GenerateScoreDetails(arg1) {
  return window['go']['main']['App']['GenerateScoreDetails'](arg1);
}

export function GetDataFromExcel(arg1, arg2) {
  return window['go']['main']['App']['GetDataFromExcel'](arg1, arg2);
}

export function GetExcelSheets(arg1) {
  return window['go']['main']['App']['GetExcelSheets'](arg1);
}

export function GetPrinterSettings() {
  return window['go']['main']['App']['GetPrinterSettings']();
}

export function InitEmployeeData(arg1, arg2) {
  return window['go']['main']['App']['InitEmployeeData'](arg1, arg2);
}

export function MessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2, arg3);
}

export function OpenDirForExcelFile() {
  return window['go']['main']['App']['OpenDirForExcelFile']();
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function PrintPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['PrintPDF'](arg1, arg2, arg3);
}

export function ReadEmployeeDataFromJsonFile(arg1) {
  return window['go']['main']['App']['ReadEmployeeDataFromJsonFile'](arg1);
}

export function ResetScoreDetails(arg1) {
  return window['go']['main']['App']['ResetScoreDetails'](arg1);
}

export function SaveEmployeeDataToJson(arg1, arg2) {
  return window['go']['main']['App']['SaveEmployeeDataToJson'](arg1, arg2);
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SelectPrintApplication() {
  return window['go']['main']['App']['SelectPrintApplication']();
}

export function UpdateEmployeeDataToJson(arg1, arg2) {
  return window['go']['main']['App']['UpdateEmployeeDataToJson'](arg1, arg2);
}
